---
name: String-Tagged
version: 0.04
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: string buffers with value tags on extents
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  String::Tagged:
    file: lib/String/Tagged.pm
    version: 0.04
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
