---
name: String-Tagged
version: 0.05
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: string buffers with value tags on extents
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  String::Tagged:
    file: lib/String/Tagged.pm
    version: 0.05
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
